### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by budx1** [kamsec/eth-keylist-checker#2]
Hey, thanks for the code, can you explain what is  "PROVIDER_ETH": "***"?

**Comment by budx1** [comment]
and i'm getting 
self.update_host(url)
    raise RuntimeError(
    RuntimeError: Timeout context manager should be used inside a task
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: ***

**Comment by kamsec** [comment]
> Hey, thanks for the code, can you explain what is "PROVIDER_ETH": "***"?

You need to set *** value as connection string from your Ethereum node provider.
alchemy.com and infura.io are popular ones and you can get that connection string for free after creating account.

Check out more at:
https://www.alchemy.com/overviews/ethereum-node-as-a-service
